export const wrap: string;
export const contentWrap: string;
export const title: string;
export const voteInfo: string;
export const colum: string;
export const cTitle: string;
export const cContent: string;
export const errPass: string;
export const input: string;
