export const wrap: string;
export const contentWrap: string;
export const title: string;
export const content: string;
export const tag: string;
export const bold: string;
export const big: string;
export const ident: string;
export const center: string;
