export const wrap: string;
export const item: string;
export const topItem: string;
export const addressItem: string;
export const aName: string;
export const arrow: string;
export const conName: string;
export const bottonTitle: string;
export const btn: string;
