/*
 * @Author: guanlanluditie 
 * @Date: 2021-03-20 20:32:25 
 * @Last Modified by: guanlanluditie
 * @Last Modified time: 2021-03-20 21:46:57
 */

export const democracyEn = {
    'Democratic Governance': 'Democratic Governance',
    'Chain referendum': 'Chain referendum',
    'Sponsor': 'Sponsor',
    'Details of the proposal': 'Details of the proposal',
    'Voting time remaining': 'Voting time remaining',
    'Voting participation': 'Voting participation',
    'support': 'support',
    'polls': 'polls',
    'oppose': 'oppose',
    'Wrong number of votes': 'Wrong number of votes',
    'Number of votes': 'Number of votes',
    'available': 'available',
    'Voting weight': 'Voting weight',
    'total': 'total',
    'next step': 'next step',
    '×0.1(Not locked)': '×0.1(Not locked)',
    '×1(Lock in for 28 days)': '×1(Lock in for 28 days)',
    '×2(Lock in for 56 days)': '×2(Lock in for 56 days)',
    '×3(Lock in for 112 days)': '×3(Lock in for 112 days)',
    '×4(Lock in for 224 days)': '×4(Lock in for 224 days)',
    '×5(Lock in for 448 days)': '×5(Lock in for 448 days)',
    '×6(Lock in for 896 days)': '×6(Lock in for 896 days)',
    'success': 'success',
    'Voting information': 'Voting information',
    'Voting proposal': 'Voting proposal',
    "Miner's fee": "Miner's fee",
    'Password confirmation': 'Password confirmation',
    'Wrong password': 'Wrong password',
    'confirm': 'confirm',
}
export const democracyZh = {
    'Democratic Governance': '民主治理',
    'Chain referendum': '链上公投',
    'Sponsor': '提案人',
    'Details of the proposal': '提案详情',
    'Voting time remaining': '投票剩余时间',
    'Voting participation': '投票参与度',
    'support': '支持',
    'oppose': '反对', 
    'polls': '票',
    'Wrong number of votes': '错误的投票额',
    'Number of votes': '投票数量',
    'available': '可用',
    'Voting weight': '投票权重',
    'total': '总计',
    'next step': '下一步',
    '×0.1(Not locked)': '×0.1(不锁定)',
    '×1(Lock in for 28 days)': '×1(需锁定28天)',
    '×2(Lock in for 56 days)': '×2(需锁定56天)',
    '×3(Lock in for 112 days)': '×3(需锁定112天)',
    '×4(Lock in for 224 days)': '×4(需锁定224天)',
    '×5(Lock in for 448 days)': '×5(需锁定448天)',
    '×6(Lock in for 896 days)': '×6(需锁定896天)',
    'success': '操作成功',
    'Voting information': '投票信息',
    'Voting proposal': '投票提案',
    "Miner's fee": '矿工费',
    'Password confirmation': '密码确认',
    'Wrong password': '密码错误',
    'confirm': '确认'
}
