export const title: string;
export const topTitle: string;
export const secInput: string;
export const btn: string;
export const btnActive: string;
export const forAgree: string;
export const checkInfo: string;
export const formTitle: string;
export const input: string;
